# Generated by Django 3.2.3 on 2021-05-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details_Discription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sort_discription',
        ),
        migrations.AddField(
            model_name='product',
            name='details_Description',
            field=models.TextField(default='atiqur', verbose_name='details_Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sort_description',
            field=models.CharField(default='ati', max_length=265, verbose_name='sort_description'),
            preserve_default=False,
        ),
    ]
